version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.9.1
      - image: circleci/redis:3.2-alpine
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "requirements_test.txt" }}
      - run:
          name: Create virtualenv and install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install_requirements
      - save_cache:
          key: v1-deps-{{ checksum "requirements_test.txt" }}
          paths:
            - "venv"
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            make pytest -- --cov=. --cov-config=.coveragerc --cov-report=html
            codecov

  flake8:
    docker:
      - image: circleci/python:3.6.6
    steps:
      - checkout
      - run:
          name: Run flake8
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install flake8
            flake8

  black:
    docker:
      - image: circleci/python:3.9.1
    steps:
      - checkout
      - run:
          name: Run Black in check mode
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install black==20.8b1
            black ./ --check

workflows:
  version: 2
  test_and_code_checks:
    jobs:
      - test
      - flake8
      - black
